#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Test Simple Class - Generated by ADAI Class Builder
"""

import cv2
import numpy as np
import time
import sys
import os

# Configurar codificación para Windows
if sys.platform.startswith('win'):
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.detach())
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.detach())

class TestSimpleClass:
    """Clase de prueba simple generada por ADAI Class Builder"""
    
    def __init__(self):
        print("="*60)
        print("ADAI - Clase de Prueba Simple")
        print("Materia: Robótica")
        print("="*60)
        
        self.class_title = "Clase de Prueba Simple"
        self.class_subject = "Robótica"
        
    def show_test_window(self):
        """Mostrar una ventana de prueba simple"""
        try:
            print("Mostrando ventana de prueba...")
            
            # Crear una imagen simple
            test_image = np.full((400, 600, 3), (100, 150, 200), dtype=np.uint8)
            
            # Agregar texto
            cv2.putText(test_image, "Clase de Prueba ADAI", (50, 50), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
            cv2.putText(test_image, "Ventana de prueba funcionando", (50, 100), 
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
            
            # Crear ventana
            cv2.namedWindow("Prueba ADAI", cv2.WINDOW_NORMAL)
            cv2.resizeWindow("Prueba ADAI", 600, 400)
            
            # Mostrar por 5 segundos
            start_time = time.time()
            while time.time() - start_time < 5:
                cv2.imshow("Prueba ADAI", test_image)
                if cv2.waitKey(100) & 0xFF == ord('q'):
                    break
            
            cv2.destroyWindow("Prueba ADAI")
            print("Ventana de prueba mostrada exitosamente")
            return True
            
        except Exception as e:
            print(f"ERROR mostrando ventana: {e}")
            return False
    
    def run(self):
        """Ejecutar la clase de prueba"""
        try:
            print("\n" + "="*60)
            print("FASE 1: INICIO")
            print("="*60)
            
            print("Iniciando clase de prueba...")
            time.sleep(1)
            
            print("\n" + "="*60)
            print("FASE 2: VENTANA DE PRUEBA")
            print("="*60)
            
            # Mostrar ventana de prueba
            self.show_test_window()
            
            print("\n" + "="*60)
            print("FASE 3: FINALIZACIÓN")
            print("="*60)
            
            print("Clase de prueba completada exitosamente")
            time.sleep(1)
            
            print("\n" + "="*60)
            print("CLASE COMPLETADA EXITOSAMENTE")
            print("="*60)
            
        except Exception as e:
            print(f"ERROR durante la ejecución: {e}")
            import traceback
            traceback.print_exc()
        finally:
            # Limpiar recursos
            cv2.destroyAllWindows()
            print("Recursos liberados")

def main():
    """Función principal"""
    print("Iniciando clase de prueba simple...")
    
    try:
        # Crear y ejecutar la clase
        clase = TestSimpleClass()
        clase.run()
        
    except KeyboardInterrupt:
        print("\nClase interrumpida por el usuario")
    except Exception as e:
        print(f"ERROR fatal: {e}")
        import traceback
        traceback.print_exc()
    finally:
        cv2.destroyAllWindows()
        print("Fin de la clase")

if __name__ == "__main__":
    main()
